plugins:
  install:
    - grafana-image-renderer

securityContext:
  runAsUser: 0
  fsGroup: 1000

extraVolumes:
  - name: plugins
    emptyDir: {}

extraVolumeMounts:
  - name: plugins
    mountPath: /opt/bitnami/grafana/data/plugins
    subPath: plugins
    readOnly: false

admin:
  user: admin
  password: your-password

persistence:
  enabled: true
  size: 10Mi

service:
  type: NodePort
  nodePorts:
    grafana: 30300

metrics:
  enabled: true

# prompts:
# - objective: updated values for grafana in the bitnami grafana chart
# - Format: Create a summary
# - Format: Use emojis
# - Format: one-line comment
# - Format: use markdown structure
# - Rewrite: Eliminate duplicate information