initContainers:
  - name: install-plugins
    image: bitnami/grafana:latest
    command:
      - grafana-cli
      - plugins
      - install
      - grafana-image-renderer
    volumeMounts:
      - name: plugins
        mountPath: /opt/bitnami/grafana/data/plugins

securityContext:
  runAsUser: 0
  fsGroup: 1000

extraVolumes:
  - name: plugins
    emptyDir: {}

extraVolumeMounts:
  - name: plugins
    mountPath: /opt/bitnami/grafana/data/plugins
    subPath: plugins
    readOnly: false

admin:
  user: admin
  password: your-password

persistence:
  enabled: true
  size: 30Mi

service:
  type: NodePort
  nodePorts:
    grafana: 30300

metrics:
  enabled: true

# prompts:
# - objective: cli install with image renderer
# - Format: Create a summary
# - Format: Use emojis
# - Format: one-line comment
# - Format: use markdown structure
# - Rewrite: Eliminate duplicate information