apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-renderer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-renderer
  template:
    metadata:
      labels:
        app: grafana-renderer
    spec:
      containers:
      - name: grafana-renderer
        image: grafana/grafana-image-renderer:latest
        ports:
          - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-renderer
spec:
  selector:
    app: grafana-renderer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000