grafana:
  adminPassword: "your-password"
  env:
    GF_RENDERING_ENABLED: "true"
    GF_RENDERING_SERVER_URL: "http://grafana-renderer:3000/render"
  persistence:
    enabled: true
    size: 100Mi
  service:
    type: NodePort
    port: 3000
  plugins:
    - grafana-image-renderer

grafanaRenderer:
  enabled: true
  image:
    repository: grafana/grafana-image-renderer
    tag: latest
  service:
    type: NodePort
    port: 3000
  replicaCount: 1

# prompt: update this to run on minikube