apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-imagerenderer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-imagerenderer
  template:
    metadata:
      labels:
        app: grafana-imagerenderer
    spec:
      containers:
      - name: grafana-imagerenderer
        image: grafana/grafana-image-renderer:latest
        ports:
        - containerPort: 8081
        volumeMounts:
        - name: grafana-renderer-storage
          mountPath: /var/lib/grafana
      volumes:
      - name: grafana-renderer-storage
        emptyDir: {}
apiVersion: v1
kind: Service
metadata:
  name: grafana-renderer
spec:
  selector:
    app: grafana-renderer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000